mongo: Change mgo package to mongo-go-driver
CESARBR/knot-cloud-storage pull request #31
Opened 2020-05-06 20:12 UTC by Igoraamc

What does this implement/fix? Explain your changes.
---------------------------------------------------
This pull request implements unit tests for all interactor features.

- Change some query entity types, to be compatible with the new driver
- Change the controller function that parses the string to int for int64
- Change the implementation of the data store to be compatible with the new driver

Does this close any currently open issues?
------------------------------------------
Any relevant logs, error output, etc?
-------------------------------------
Any other comments?
-------------------
Where has this been tested?
---------------------------

**Operating System/Platform:** MACOS Catalina

**GO Version:** go 1.13.7 darwin/amd64

2020-05-06 21:01 UTC, netoax requested changes
Thanks for the PR, it seems ok for me. Please, just update the last line of the commit message in order to respect the 50/72 rule.

TIP: It's advisable to write dissertation-like messages, describing the main **motivation** and **what** changed (not how). Of course, you can if necessary use dashes or bullet points to explain topics or a list of things after describing the motivation.

2020-05-06 21:01 UTC, netoax commented on pkg/data/data_store.go
> +
Please, remove this blank line.

2020-05-06 21:01 UTC, netoax commented on pkg/data/data_store.go
> +func (ds *store) getFindOptions(query *entities.Query) *options.FindOptions {
Very good! 👍

2020-05-07 08:54 UTC, Igoraamc commented on pkg/data/data_store.go
> +
Done!

2020-05-07 08:54 UTC, Igoraamc commented on pkg/data/data_store.go
> +func (ds *store) getFindOptions(query *entities.Query) *options.FindOptions {
Thank you!

2020-05-07 22:36 UTC, lcbm approved these changes
LGTM! 😄

2020-05-08 17:18 UTC, netoax approved these changes
LGTM!

2020-05-08 17:18 UTC, merged